Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.graphics_type = 'none'
    libvirt.memory = 1048
    libvirt.cpus = 1
    libvirt.storage :file, :size => '10G'
    libvirt.qemu_use_session = false
  end
  # node1.
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "generic/centos7"
    node1.vm.disk :disk, size: "10GB", primary: true
    node1.vm.provision "shell", path: "ssh/config.sh"
    node1.vm.provision "shell", path: "basic/config.sh"
    #node1.vm.network :public_network, ip: "192.168.121.30"
  end
  # # node2.
  # config.vm.define "node2" do |node2|
  #   node2.vm.hostname = "node2"
  #   node2.vm.box = "centos/7"
  #   node2.vm.disk :disk, size: "10GB", primary: true
  #   node2.vm.network :private_network, ip: "192.168.100.20"
  # end
end
