Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.graphics_type = 'none'
    libvirt.memory = 1048
    libvirt.cpus = 1
    libvirt.storage :file, :size => '10G'
    libvirt.qemu_use_session = false
  end
  # node1.
  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.box = "generic/centos7"
    node1.vm.provision "shell", path: "ssh/config.sh"
    node1.vm.provision "shell", path: "basic/config.sh"
  end
  # node2.
  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.box = "generic/centos7"
    node2.vm.provision "shell", path: "ssh/config.sh"
    node2.vm.provision "shell", path: "basic/config.sh"
  end
end
