
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.graphics_type = 'none'
    libvirt.memory = 1048
    libvirt.cpus = 1
    libvirt.storage :file, :size => '10G'
    libvirt.qemu_use_session = false
    

  end
  # master
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.provision "shell", inline: "hostnamectl set-hostname master"
    master.vm.provision "shell", path: "basic/config.sh"
    master.vm.provision "shell", path: "docker/setup.sh"
    master.vm.provision "shell", path: "kube/setup.sh"
    master.vm.provision "shell", path: "kube/master.sh"
  end
  config.trigger.after :up do |trigger|
    trigger.info = "Post config !!"
    trigger.run = {inline: "bash -c 'sshpass -p 'root' scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r root@master:/etc/kubernetes/admin.conf ~/.kube/config'"}
  end

  # Worker
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.provision "shell", inline: "hostnamectl set-hostname worker"
    worker.vm.provision "shell", path: "basic/config.sh"
    worker.vm.provision "shell", path: "docker/setup.sh"
    worker.vm.provision "shell", path: "kube/setup.sh"
    worker.vm.provision "shell", path: "kube/worker.sh"
   end
end
